matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install selenium
      before_script:
        - echo "Hola"
      addons:
        sauce_connect:
          username: "yanahini"
          access_key: "2d974dfe-e7c2-456e-ad52-4af1ef9531c5"
      script:
        python test_selenium.py
     
